import tecno1 from '../assets/tecno1.jpg'

const miniDatabase = {
    users: [
      {
        id: 1,
        username: "admin",
        password: "admin123",
        role: "admin",
        email: "admin@example.com",
      },
      {
        id: 2,
        username: "johnDoe",
        password: "john123",
        role: "customer",
        email: "johndoe@example.com",
      },
      {
        id: 3,
        username: "janeSmith",
        password: "jane123",
        role: "customer",
        email: "janesmith@example.com",
      },
    ],
    products: [
      {
        id: 1,
        name: "Smartphone Pro",
        description: "A sleek smartphone with the latest features.",
        price: 999.99,
        category: "Electronics",
        stock: 50,
        image: {tecno1},
        flavors: ["14 inches", "16 inches", "22 inches" ],
        flavorText: "Choose a size"
      },
      {
        id: 2,
        name: "Leather Jacket",
        description: "A stylish leather jacket for all seasons.",
        price: 199.99,
        category: "Fashion",
        stock: 30,
        image: {tecno1},
        flavors: ["14 inches", "16 inches", "22 inches" ],
        flavorText: "Choose a size"
      },
      {
        id: 3,
        name: "Gourmet Coffee",
        description: "Premium quality coffee beans.",
        price: 19.99,
        category: "Groceries",
        stock: 100,
        image: "/images/gourmet-coffee.jpg",
        flavors: ["Vanilla", "Hazelnut", "Caramel"],
        flavorText: "Choose a flavour"
      },
      {
        id: 4,
        name: "Wireless Earbuds",
        description: "High-quality sound with noise cancellation.",
        price: 79.99,
        category: "Electronics",
        stock: 75,
        image: "/images/wireless-earbuds.jpg",
        flavors: [],
      },
      {
        id: 5,
        name: "Cooking Pan Set",
        description: "Durable and non-stick cooking pans.",
        price: 59.99,
        category: "Home",
        stock: 40,
        image: "/images/cooking-pan.jpg",
        flavors: [],
      },
      {
        id: 6,
        name: "Sports Shoes",
        description: "Comfortable and durable running shoes.",
        price: 89.99,
        category: "Fashion",
        stock: 60,
        image: "/images/sports-shoes.jpg",
        flavors: [],
      },
      {
        id: 7,
        name: "Blender",
        description: "Powerful blender for smoothies and more.",
        price: 39.99,
        category: "Home",
        stock: 25,
        image: "/images/blender.jpg",
        flavors: [],
      },
      {
        id: 8,
        name: "Fiction Book",
        description: "An engaging story from a bestselling author.",
        price: 14.99,
        category: "Books",
        stock: 120,
        image: "/images/fiction-book.jpg",
        flavors: [],
      },
      {
        id: 9,
        name: "Gaming Chair",
        description: "Ergonomic and comfortable chair for gamers.",
        price: 149.99,
        category: "Furniture",
        stock: 20,
        image: "/images/gaming-chair.jpg",
        flavors: [],
      },
      {
        id: 10,
        name: "Ice Cream",
        description: "Creamy ice cream in multiple flavors.",
        price: 5.99,
        category: "Groceries",
        stock: 200,
        image: "/images/ice-cream.jpg",
        flavors: ["Chocolate", "Vanilla", "Strawberry"],
      },
    ],
    orders: [
      {
        id: 101,
        userId: 2,
        products: [
          { productId: 1, quantity: 1 },
          { productId: 3, quantity: 2 },
        ],
        total: 1039.97,
        status: "Completed",
        date: "2025-01-12",
      },
      {
        id: 102,
        userId: 3,
        products: [
          { productId: 5, quantity: 1 },
          { productId: 10, quantity: 3 },
        ],
        total: 22.96,
        status: "Processing",
        date: "2025-01-12",
      },
    ],
  };

export default miniDatabase
  